/*
 * File: app/store/countrystore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.mem.orderStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.mem.orderModel'
    ],

    config: {
        model: 'MyApp.model.mem.orderModel',
        storeId: 'OrderStore',
        pageSize: 999,
        proxy: {
            type: 'ajax',
            extraParams:{task: "action", action: 'member.order.getOrdersMobile',controller:'member'},
            url: getCurrentUrl()+'index.php?option=com_osemsc',
            reader: {
                type: 'json',
                idProperty: 'id',
                rootProperty: 'results'
            }
        },
        autoLoad:{}
    }
});