/*
 * File: app/view/AddonView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AddonView', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.addonview',
    addons:[],
    config: {
    	store: {
            fields: [
               {
	                name: 'id',
	                mapping: 'id',
	                type: 'int'
	            },
	            {
	                name: 'title',
	                mapping: 'title',
	                type: 'string'
	            },
	            {
	                name: 'name',
	                mapping: 'name',
	                type: 'string'
	            }
            ]
        },
        useComponents: false,
        itemTpl: [
            //'<div style="text-align:center;min-height:48px;width:80px;font-family:"Segoe UI", Helvetica, sans-serif;float:left;margin-right:10px;cursor:pointer;padding:64px 0 0">',
	        //'<div>',
            '<div class="ose-icon-addon" style="float:left;min-height:48px;width:80px;margin:15px 15px 15px 15px;font-family:Segoe UI, Helvetica, sans-serif;cursor:pointer;padding:32px 0 0">',    
            	'<div class="ose-icon-{name}" style="min-height:48px;width:80px;">','</div>',
	            '<span><strong>{title}</strong></span>',
	            //'</div>',
            //'</div>',
            '</div>'
        ],
        listeners: [
            {
                fn: 'onDataviewItemSingleTap',
                event: 'itemsingletap'
            },{
            	fn: 'onDataviewItemInitialize',
                event: 'initialize'
            }
        ]
    },

    onDataviewItemSingleTap: function(dataview, index, target, record, e, options) {
    	var nav = dataview.up('navigationview');
    	nav.setMasked({
    		xtypp: 'loadmask'
    	});
    	nav.push({
    		xtype: record.get('name'),
    		title: record.get('title')
    	});
    	nav.setMasked(false);
    },
    
    onDataviewItemInitialize: function(dataview) {
    	
    }

});