/*
 * File: app/view/ConfirmPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.ns('oseMsc');
oseMsc.formSuccess = function(form,action)	{
	var msg = action.result;
	Ext.Msg.setAlert(msg.title,msg.content);
}

oseMsc.formFailure = function(form,action)	{
	if (action.failureType === Ext.form.Action.CLIENT_INVALID){
		oseMsc.msg.setAlert(Joomla.JText._('Notice'),Joomla.JText._('Please_check_the_notice_in_the_form'));
    }

	if (action.failureType === Ext.form.Action.CONNECT_FAILURE) {
       Ext.Msg.alert('Error',
        'Status:'+action.response.status+': '+
        action.response.statusText);

    }

    if (action.failureType === Ext.form.Action.SERVER_INVALID){
        var msg = action.result;
		oseMsc.msg.setAlert(msg.title,msg.content);
    }
}

oseMsc.formSuccessMB = function(form,action,func)	{
	var msg = action.result;
	Ext.Msg.show({
	   title: msg.title
	   ,msg: msg.content
	   ,width: 600
	   ,buttons: Ext.MessageBox.OK
	   //,multiline: true
	   ,fn: func
	   //,prompt
	   //,closable: false
	   //,animEl: 'addAddressBtn'
	   ,icon: Ext.MessageBox.INFO
	});
	//Ext.Msg.alert(msg.title,msg.content,func	);
}

oseMsc.formFailureMB = function(form,action,func)	{
	if (action.failureType === Ext.form.Action.CLIENT_INVALID){
		Ext.Msg.alert(Joomla.JText._('Notice'),Joomla.JText._('Please_check_the_notice_in_the_form'));
    }

	if (action.failureType === Ext.form.Action.CONNECT_FAILURE) {
       Ext.Msg.alert('Error',
        'Status:'+action.response.status+': '+
        action.response.statusText);

    }

    if (action.failureType === Ext.form.Action.SERVER_INVALID){
        var msg = action.result;
        //Ext.Msg.alert(msg.title,msg.content	,func);


		Ext.Msg.show({
			title: msg.title
			,msg: msg.content
			,buttons: Ext.Msg.OK
			,fn:func
			,closable: false
		});

    }
}

Ext.define('MyApp.view.ConfirmPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.confirmpanel',
    formid: '',
    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Order Confirmation',
                layout: {
                   // pack: 'end',
                    type: 'hbox'
                },
                items: [
                    {
                    	xtype: 'button',
                        ui: 'decline',
                        text: 'Close',
                        handler: function(btn)	{
                        	var cp = btn.up('confirmpanel');
                        	cp.destroy();
                        }
                    },
                    {
                    	xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'confirm',
                        text: 'Confirm',
                        handler: function(btn)	{
                        	var cp = btn.up('confirmpanel');
                        	var fp = Ext.getCmp(cp.formid);
                        	var fi = getFormItems();
                        	var fv = fp.getValues();
                        	var submit = true;
                        	// close panel first, bug here;
                        	cp.destroy();
                        	Ext.each(fi,function(item,i,all)	{
                        		var message = '';
                        		var mn = 'MyApp.model.'+item.xtype;
                        	
	                        		if(Ext.ModelManager.isRegistered(mn))	{
	                        			var instance = Ext.create(mn,fv);
	                                    var errors = instance.validate();
	                                    
	                                    if(errors.isValid()){
	                                    	
	                                    }	else	{
	                                    	Ext.each(errors.items,function(rec,i){
	                                            message += rec.getField()+':'+rec.getMessage()+"<br>";
	                                        });
	                                        Ext.Msg.alert("Validate", message, function(){});
	                                        submit = false;
	                                        return false;
	                                    }
	                        		}
                        		
                        	});
                        	
                        	if(submit)	{
                        		fp.submit({
                        			waitMsg : {message:'Submitting'},
                        			url: 'index.php?option=com_osemsc',
                        			params: {controller: 'register',task:'saveMobile'},
                        			success: function(form,result)	{
                        				this.onPaymentSuccess(form,result);
                        			},
                        			failure: function(form,result)	{
                        				this.onPaymentFailure(form,result);
                        			},
                        			scope: cp
                                });
                        	}
                        }
                    }
                ]
            }
        ]
    }

	,onPaymentSuccess: function(form,result)	{
		var msg = result;
		var payment_method = msg.payment_method;
	
		var onProcessPayment = function(payment_method)	{
			switch(payment_method)	{
				case('paypal'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('paypal_image').dom.click();
				break;
	
				case('paypal_cc'):
					//confirmWin.body.unmask();
					if(Ext.value(msg.code,false) !== false)	{
						eval(msg.code);
					}
					Ext.Msg.alert(msg.title,msg.content,function(btn,text){
						if(btn == 'ok')	{
							if(typeof(msg.returnUrl) == 'undefined')	{
								window.location = 'index.php?option=com_osemsc&view=member'
							}	else	{
								window.location = msg.returnUrl
							}
						}
					})
				break;
	
				case('none'):
					//confirmWin.body.unmask();
					Ext.Msg.alert(msg.title,msg.content,function(btn,text){
						if(btn == 'ok')	{
							if(typeof(msg.returnUrl) == 'undefined')	{
								window.location = 'index.php?option=com_osemsc&view=member'
							}	else	{
								window.location = msg.returnUrl
							}
						}
					})
				break;
	
				case('poffline'):
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined'){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
							if(btn == 'ok')	{
								if(typeof(msg.returnUrl) == 'undefined')	{
									window.location = 'index.php?option=com_osemsc&view=member'
								}	else	{
									window.location = msg.returnUrl
								}
							}
						})
					}else{
						window.location = msg.returnUrl;
					}
				break;
	
				case('epay'):
					//window.location = msg.html.url;
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('epay_button').dom.click();
				break;
	
				case('pnw'):
					//window.location = msg.html.url;
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('submit_button').dom.click();
				break;
	
				case('vpcash_cc'):
				case('vpcash'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('vpcash_image').dom.click();
				break;
	
				case('bbva'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('bbva_image').dom.click();	
				break;
	
				case('gco'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('gco_image').dom.click();	
				break;
	
				case('payfast'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('payfast_image').dom.click();
				break;
	
				case('ewaysh'):
					if(msg.success == false){
	
					}else{
						window.location = msg.html;
					}
				break;
	
				case('2co'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('2co_image').dom.click();
				break;
	
				case('clickbank'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('clickbank_image').dom.click();
				break;
	
				case('ccavenue'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('ccavenue_image').dom.click();
				break;
	
				case('usaepay'):
					
					if(typeof(msg.code) != 'undefined'){
						eval(msg.code);
					}
					if(typeof(msg.htmlTrack) != 'undefined')	{
						eval(msg.htmlTrack);
					}
					
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined'){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
							if(btn == 'ok')	{
								if(typeof(msg.returnUrl) == 'undefined')	{
									window.location = 'index.php?option=com_osemsc&view=register'
								}	else	{
									window.location = msg.returnUrl
								}
							}
						})
					}
				break;
	
				case('icepay'):
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined' && msg.success == false){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
	
						})
					}else if(typeof(msg.html) != 'undefined') {
						window.location = msg.html
					}
				break;
	
				case('oospay'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('oospay_image').dom.click();
				break;
	
				case('ebs'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('ebs_image').dom.click();
				break;
	
				case('liqpay'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('liqpay_image').dom.click();
				break;
	
				case('virtualmerchant'):
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined'){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
							if(btn == 'ok')	{
								if(typeof(msg.returnUrl) == 'undefined')	{
									window.location = 'index.php?option=com_osemsc&view=register'
								}	else	{
									window.location = msg.returnUrl
								}
							}
						})
					}
				break;
	
				case('realex_redirect'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('realex_image').dom.click();
				break;
	
				case('realex_remote'):
					
					if(typeof(msg.code) != 'undefined'){
						eval(msg.code);
					}
					if(typeof(msg.htmlTrack) != 'undefined')	{
						eval(msg.htmlTrack);
					}
					
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined'){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
							if(btn == 'ok')	{
								if(typeof(msg.returnUrl) == 'undefined')	{
									window.location = 'index.php?option=com_osemsc&view=register'
								}	else	{
									window.location = msg.returnUrl
								}
							}
						})
					}
				break;
	
				case('sisow'):
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined'){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
							if(btn == 'ok')	{
								if(typeof(msg.returnUrl) == 'undefined')	{
									window.location = 'index.php?option=com_osemsc&view=register'
								}	else	{
									window.location = 'index.php?option=com_osemsc&view=register';
								}
							}
						})
					}else{
						if(typeof(msg.url) != 'undefined')
						{
							window.location = msg.url;
						}
					}
				break;
				
				case('pagseguro'):
					if(typeof(msg.title) != 'undefined' && typeof(msg.content) != 'undefined'){
						Ext.Msg.alert(msg.title,msg.content,function(btn,text){
							if(btn == 'ok')	{
								if(typeof(msg.returnUrl) == 'undefined')	{
									window.location = 'index.php?option=com_osemsc&view=register'
								}	else	{
									window.location = 'index.php?option=com_osemsc&view=register';
								}
							}
						})
					}else{
						window.location = msg.url;
					}
	
				break;
				
				case('paygate'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('paygate_image').dom.click();
				break;
				
				case('quickpay'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('quickpay_image').dom.click();
				break;
				
				case('sagepay'):
					Ext.get('ose-payment-callback-form').setHtml(msg.html.form);
					Ext.get('sagepay_image').dom.click();
				break;
				
				default:
					//confirmWin.body.unmask();
					
					if(typeof(msg.code) != 'undefined'){
						eval(msg.code);
					}
					if(typeof(msg.htmlTrack) != 'undefined')	{
						eval(msg.htmlTrack);
					}
					Ext.Msg.alert(msg.title,msg.content,function(btn,text){
						if(btn == 'ok')	{
							if(typeof(msg.returnUrl) == 'undefined')	{
								window.location = 'index.php?option=com_osemsc&view=member'
							}	else	{
								window.location = msg.returnUrl
							}
						}
					})
				break;
			}
		}
		
		if((msg.activation != false || typeof(msg.activation) == 'undefined') && payment_method != 'poffline' && payment_method != 'none')
		{
			Ext.Msg.show({
				   msg: msg.content
				   ,width: 600
				   ,buttons: {ok:Joomla.JText._('PROCEED')}
				   ,fn: function(btn,text){
						if(btn == 'ok')	{
							onProcessPayment(payment_method);
						}
					}
				   ,icon: Ext.MessageBox.INFO
			});
		}else{
			onProcessPayment(payment_method);
		}	
	}
	
	,onPaymentFailure: function(form,result)	{
		var msg = result;
		Ext.Msg.alert(msg.title,msg.content,function(){
			if( typeof(msg.script) == 'undefined' || msg.script == false )	{
				if(msg.reload == true)	{
					oseMsc.reload();
				}else{
					this.destroy();
				}
			}	else	{
				this.destroy();
				form.findField(msg.field).focus();
			}
		},this)
	}
});