/*
 * File: app/view/login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.logout', {
    extend: 'Ext.form.Panel',
    alias: 'widget.logoutform',

    config: {
        items: [
            {
                xtype: 'button',
                text: 'Logout',
                itemId: 'logout',
                width: 200
            }
        ],
        listeners: [
            {
                fn: 'onLogoutTap',
                event: 'tap',
                delegate: '#logout'
            }
        ]
    },
    
    onLogoutTap: function(button, e, options) {
        var fp = button.up('formpanel');
        fp.submit({
            url: getCurrentUrl()+'index.php?option=com_osemsc',
            params: {controller: 'register',task:'logout'},
            success: function(form,result){
            	var msg = result;
            	Ext.Viewport.setMasked(true);
            	//Ext.Msg.wait(Joomla.JText._('Redirecting_please_wait'),Joomla.JText._('Login_Successfully'));
				window.location = msg.returnUrl;
            },
            failure: function(form,result){
            	var msg = result;
            	Ext.Msg.alert(msg.title, msg.content, function(){});
            }
        })
    }

});