/*
 * File: app/view/MemberPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MemberPanel', {
    extend: 'Ext.navigation.View',
    alias: 'widget.testddd',
    
    config: {
        items: [
            {
                xtype: 'tabpanel',
                title: 'Welcome',
                tabBarPosition: 'bottom',
                listeners: { 
                	initialize: function(f)	{
                		var tabs = getMemTypes();
                		var addons = getAddons();

                		Ext.each(tabs,function(item,i,all)	{
                			var addon = Ext.create('MyApp.view.AddonView',{
                				title: item.title
                			});
                			addon.getStore().setData(addons[item.type]);
                			f.add(addon);
                		});
                	}
                }
            }
        ],
        navigationBar: {
        	items: [{
        		xtype: 'button',
        		text: 'Exit',
        		itemId: 'exitbutton',
        		ui: 'back',
        		handler: function(btn)	{
        			window.history.back();
        		}
        	}]
        },
        listeners: [
            {
                fn: 'onBack',
                event: 'back'
            },
            {
                fn: 'onPush',
                event: 'push'
            }
        ]
    },
    
    onBack: function(view,eopts)	{
    	var bar = view.getNavigationBar();
    	if(bar.down('#savebutton') != null)	{
    		bar.down('#savebutton').destroy();
    	}
    	bar.add({
    		xtype: 'button',
    		text: 'Exit',
    		itemId: 'exitbutton',
    		ui: 'back',
    		handler: function(btn)	{
    			window.history.back();
    		}
    	});
    },
    
    onPush: function(nav,view,eopts)	{
    	var bar = nav.getNavigationBar();
    	if(bar.down('#exitbutton') != null)	{
    		bar.down('#exitbutton').destroy();
    	}
    }

});
