/*
 * File: app/view/UserRegForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UserRegForm', {
    extend: 'Ext.form.Panel',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Payment',
                items: [
                    {
                    	xtype: 'button',
                    	text: 'Back',
                    	ui: 'back',
                    	handler: function(btn)	{
                    		window.history.back();
                    	}
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        text: 'Save',
                        itemId: 'save',
                        ui: 'confirm',
                        handler: function(btn){
                        	var fid = btn.up('formpanel').getId();
                        	var params = btn.up('formpanel').getValues();
                        	params.controller = 'register';
                        	params.task = 'generateConfirmDialog';
                        	Ext.Ajax.request({
                        		url: getCurrentUrl()+'index.php?option=com_osemsc',
                        		params: params,
                        		success: function(response){
                    		        var text = response.responseText;
                    		        // process server response here
                    		        var cp = Ext.create('MyApp.view.ConfirmPanel',{
                                		hideOnMaskTap: true,
                                		width: '80%',
                                		height: '70%',
                                		modal: true,
                                		html: text
                                	});
                                	cp.formid = fid;
                                	cp.showBy(btn);
                    		    }
                        	});
                        }
                    }
                ]
            }
        ],
        listeners: {
        	initialize: function(f)	{
        		var me = this;
        		f.add(getFormItems());
        		
        		if(getTerms().length > 0){
        			f.down('#save').setDisabled(true);
        		}
        		
        		// load Info
        		var reg = getRegInfo();
        		me.setValues(reg);
        		
        	},
        	
        	painted: function(f)	{
        		var me = this;
        		
        	
        	}
        }
    }

});