/*
 * File: app/view/BillingFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.reg.BillingFieldset', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.billinginfo',
    requires:['MyApp.field.HolderSelect'],
    config: {
        title: Joomla.JText._('Billing_Information'),
        items: [
            {
                xtype: 'textfield',
                label: Joomla.JText._('First_Name'),
                itemId: 'firstname',
                name: 'bill_firstname'
            },
            {
                xtype: 'textfield',
                label: Joomla.JText._('Last_Name'),
                name: 'bill_lastname'
            },
            {
                xtype: 'textareafield',
                label: Joomla.JText._('Billing_Address'),
                name: 'bill_addr1'
            },
            {
                xtype: 'textareafield',
                label: Joomla.JText._('Billing_Address_Line2'),
                name: 'bill_addr2'
            },
            {
                xtype: 'textfield',
                label: Joomla.JText._('Billing_CITY'),
                name: 'bill_city'
            },
            {
                xtype: 'textfield',
                label: Joomla.JText._('Billing_Postal_Code'),
                name: 'bill_postcode'
            },
            {
                label: Joomla.JText._('Billing_Country'),
                name: 'bill_country',
                xtype: 'holderselectfield',
                displayField: 'name',
        		valueField: 'abbr',
        		placeHolder: 'Please Choose',
        		required: true,
                store: {
                	fields: [
      					{name:'abbr',type:'string',mapping:'country_3_code'}
      					,{name:'name',type:'string',mapping:'country_name'}
      					,{name:'country_id',type:'int',mapping:'country_id'}
      				]
      			    ,data : getCountry().results
                },
                listeners: {
			    	change: function(f,nv,ov)	{
			    		var rec = f.getRecord();
			    		var state = f.up('billinginfo').down('#state');
			    		var store = state.getStore();
			    		store.clearFilter();
			    		store.filterBy(function(srec,id){
			    			return (srec.get('country_id') == rec.get('country_id'));
			    		});
			    	}
				    
	            }
            },
            {
                xtype: 'holderselectfield',
                label: Joomla.JText._('Billing_STATE'),
                name: 'bill_state',
                itemId: 'state',
                displayField: 'name',
        		valueField: 'abbr',
        		placeHolder: 'Please Choose',
        		required: true,
                store: {
                	fields: [
      					{name:'abbr',type:'string',mapping:'state_2_code'}
      					,{name:'name',type:'string',mapping:'state_name'}
      					,{name:'state_id',type:'int',mapping:'state_id'}
      					,{name:'country_id',type:'int',mapping:'country_id'}
      				]
      			    ,data : getState().results
      			    
                },
            	listeners: {
			    	initialize: function(f)	{
			    		f.getStore().filterBy(function(rec,id){
			    			return (rec.get('country_id') == 0);
			    		});
			    	}
			    }
            }
        ]
    }

});