/*
 * File: app/view/JuserFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.reg.JuserFieldset', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.juser',

    alternateClassName: [
        'juserfieldset'
    ],

    config: {
        title: Joomla.JText._('User_Account'),
        items: [
            {
                xtype: 'textfield',
                label: 'Name',
                name: 'juser_name'
            },
            {
                xtype: 'textfield',
                label: Joomla.JText._('Username'),
                name: 'juser_username',
                required: true
            },
            {
                xtype: 'emailfield',
                label: Joomla.JText._('Email'),
                name: 'juser_email',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                itemId: 'password',
                label: Joomla.JText._('Password'),
                name: 'juser_password1'
            },
            {
                xtype: 'passwordfield',
                itemId: 'mypasswordfield1',
                label: Joomla.JText._('Password_Confirm'),
                name: 'juser_password2'
            }
        ],
        listeners: [
            {
                fn: 'onMypasswordfield1Blur',
                event: 'blur',
                delegate: '#mypasswordfield1'
            }
        ]
    },

    onMypasswordfield1Blur: function(textfield, e, options) {
       
    }

});