/*
 * File: app/view/JuserFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.reg.MscList', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.msc_list',
    requires:['MyApp.field.HolderSelect'],
    config: {
        title: 'MSC List',
        items: [
            {
                label: Joomla.JText._('Membership_List'),
                name: 'country',
                xtype: 'holderselectfield',
                name:'msc_id',
                displayField: 'name',
        		valueField: 'abbr',
        		placeHolder: 'Please Choose',
        		required: true,
                store: {
                	fields: [
      					{name:'abbr',type:'int',mapping:'id'}
      					,{name:'name',type:'string',mapping:'title'}
      				]
      			    ,data : getMscList().results
                },
                listeners: {
			    	change: function(f,nv,ov)	{
			    		var rec = f.getRecord();
			    		var option = f.up('msc_list').down('#msc_option');
			    		var store = option.getStore();
			    		store.clearFilter();
			    		store.filterBy(function(srec,id){
			    			return (srec.get('msc_id') == nv);
			    		});
			    	}
				    
	            }
            },
            {
                xtype: 'holderselectfield',
                label: Joomla.JText._('Membership_Option'),
                name: 'msc_option',
                itemId: 'msc_option',
                displayField: 'name',
        		valueField: 'abbr',
        		placeHolder: 'Please Choose',
        		required: true,
                store: {
                	fields: [
      					{name:'abbr',type:'string',mapping:'id'}
      					,{name:'name',type:'string',mapping:'title'}
      					,{name:'msc_id',type:'int',mapping:'msc_id'}
      				]
      			    ,data : getMscOption().results
      			    
                },
            	listeners: {
			    	initialize: function(f)	{
			    		f.getStore().filterBy(function(rec,id){
			    			return (rec.get('id') == 0);
			    		});
			    	}
			    }
            }
        ]
    }

});