/*
 * File: app/view/paymentFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCContainer', {
    extend: 'Ext.Container',
    alias: 'widget.cccontainer',
    config: {
        //title: Joomla.JText._('Payment'),
        items: [
			{
				xtype: 'container',
			    layout: {
			        type: 'hbox'
			    },
			    items: [
			        {
			        	xtype: 'holderselectfield',
		                label: Joomla.JText._('Credit_Card'),
		                flex: 1,
		                name: 'creditcard_type',
		                placeHolder: 'Please Choose',
		                displayField: 'name',
		        		valueField: 'abbr',
		                store: {
		                	fields: [
		      					{name:'abbr',type:'string',mapping:'value'}
		      					,{name:'name',type:'string',mapping:'text'}
		      				]
		      			    ,data : [
		      			        {value:'VISA',text:'Visa'}
		      			        ,{value:'MC',text:'MasterCard'}
		    			        	//,['amex','American Express']
		    			        	//,['discover','Discover Card']
					        ]
		                }
			        },
			        {
			        	cls: 'credicardimg',
						border: false,
						width: 120,
						styleHtmlContent: true
			        }
			    ]
			},
            {
                xtype: 'textfield',
                label: Joomla.JText._('NAME_ON_CARD'),
                name: 'creditcard_name'
            },
            {
                xtype: 'textfield',
                label: Joomla.JText._('Credit_Card_Number'),
                name: 'creditcard_number'
            },
            {
                xtype: 'datepickerfield',
                label: Joomla.JText._('Expiration_Date'),
                name: 'creditcard_expirationdate',
                placeHolder: 'mm/yyyy',
                dateFormat: 'Y-m',
                picker: {
                    slotOrder: [
                        'month',
                        'year'
                    ],
                    yearFrom: 2012,
                    yearTo: 2020
                }
            },
            {
            	xtype: 'container',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                    	 xtype: 'textfield',
                    	 flex: 1,
                         label: Joomla.JText._('Security_Code'),
                         name: 'creditcard_cvv'
                    },
                    {
                        xtype: 'button',
                        width: 180,
                        text: Joomla.JText._('WHAT_IS_THIS'),
                        handler: function(btn)	{
                        	Ext.create('Ext.Panel',{
                        		html: Joomla.JText._('WHAT_IS_THIS_EXP'),
                        		width: 300,
                        		height: 200,
                        		hideOnMaskTap:true,
                        		modal: true
                        	}).showBy(btn);
                        }
                    }
                ]
            }
        ]
    }

});

Ext.define('MyApp.view.reg.paymentFieldset', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.payment',
    config: {
        title: Joomla.JText._('Payment'),
        defaults: {
            //labelWidth: 250
        },
        items: [
            {
            	xtype: 'holderselectfield',
                //flex: 1,
                label: Joomla.JText._('Payment_Method'),
                //labelWidth: 250,
                name: 'payment_payment_method',
                itemId: 'payment_method',
                placeHolder: 'Please Choose',
            	displayField: 'name',
        		valueField: 'abbr',
        		required: true,
                store: {
                	fields: [
      					{name:'abbr',type:'string',mapping:'value'}
      					,{name:'name',type:'string',mapping:'text'}
      					,{name:'id',type:'int',mapping:'id'}
      				]
      			    ,data : getPaymentMethod().results
                },
                listeners: {
			    	change: function(f,nv,ov)	{
			    		var rec = f.getRecord();
			    		var cc = f.up('payment').down('#cccontainer');

			    		if(rec.get('id') == 4)	{
                			f.up('payment').add({
                				xtype: 'cccontainer',
                                itemId: 'cccontainer',
                                defaults: {
                                    //labelWidth: 250
                                }
                			})
                		}	else	{
                			if(f.up('payment').down('#cccontainer') != null)	{
                				f.up('payment').down('#cccontainer').destroy();
                			}
                		}
			    	}
	            }
            }
        ]
    }

});