/*
 * File: app/view/BillingFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BillingFieldset', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.billing',

    config: {
        title: 'Billing Info.',
        items: [
            {
                xtype: 'textfield',
                label: 'First Name',
                name: 'firstname'
            },
            {
                xtype: 'textfield',
                label: 'Last Name',
                name: 'lastname'
            },
            {
                xtype: 'textareafield',
                label: 'Address 1',
                name: 'addr1'
            },
            {
                xtype: 'textareafield',
                label: 'Address 2',
                name: 'addr2'
            },
            {
                xtype: 'selectfield',
                label: 'Country',
                name: 'country'
            },
            {
                xtype: 'selectfield',
                label: 'State',
                name: 'state'
            },
            {
                xtype: 'textfield',
                label: 'Postcode',
                name: 'postcode'
            }
        ]
    }

});