/*
 * File: app/view/JuserFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.JuserFieldset', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.juser',

    alternateClassName: [
        'juserfieldset'
    ],

    config: {
        title: 'JUser',
        items: [
            {
                xtype: 'textfield',
                label: 'Name',
                name: 'name'
            },
            {
                xtype: 'textfield',
                label: 'Username',
                name: 'username',
                required: true
            },
            {
                xtype: 'emailfield',
                label: 'Email',
                name: 'email',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                itemId: 'password',
                label: 'Password',
                name: 'password'
            },
            {
                xtype: 'passwordfield',
                itemId: 'mypasswordfield1',
                label: 'Password Confirm',
                name: 'password1'
            }
        ],
        listeners: [
            {
                fn: 'onMypasswordfield1Blur',
                event: 'blur',
                delegate: '#mypasswordfield1'
            }
        ]
    },

    onMypasswordfield1Blur: function(textfield, e, options) {
        var fp = textfield.up('formpanel');
        var pwd = fp.down('#password');
        if(textfield.getValue() != pwd.getValue()){

        }
    }

});