/*
 * File: app/view/paymentFieldset.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.paymentFieldset', {
    extend: 'Ext.form.FieldSet',

    config: {
        title: 'Payment Method(s)',
        defaults: {
            labelWidth: 250
        },
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'selectfield',
                        flex: 1,
                        label: 'Payment Method(s)',
                        labelWidth: 250,
                        name: 'payment',
                        placeHolder: 'Please Choose'
                    },
                    {
                        xtype: 'container',
                        width: 300
                    }
                ]
            },
            {
                xtype: 'container',
                defaults: {
                    labelWidth: 250
                },
                items: [
                    {
                        xtype: 'selectfield',
                        label: 'Credit Card',
                        name: 'creditcard_type',
                        placeHolder: 'Please Choose'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Credit Card Number',
                        name: 'creditcard_number'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Expiration Date',
                        name: 'expiration_date',
                        placeHolder: 'mm/dd/yyyy',
                        picker: {
                            slotOrder: [
                                'month',
                                'year'
                            ],
                            yearFrom: 2012,
                            yearTo: 2020
                        }
                    },
                    {
                        xtype: 'textfield',
                        label: 'Security Code',
                        name: 'cvv_code'
                    }
                ]
            }
        ]
    }

});