/*
 * File: app/view/TermsItem.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TermsItem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.termsitem',

    config: {
        padding: 10,
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'container',
                width: '100%',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'checkboxfield',
                        height: 53,
                        width: 65
                    },
                    {
                        xtype: 'container',
                        html: 'I agree to',
                        styleHtmlContent: true
                    },
                    {
                        xtype: 'container',
                        flex: 1
                    }
                ]
            }
        ]
    },

    updateRecord: function(record) {
        // Provide an implementation to update this container's child items
    }

});