<?php/**  * @version     5.0 +  * @package        Open Source Membership Control - com_osemsc  * @subpackage    Open Source Access Control - com_osemsc  * @author        Open Source Excellence (R) {@link  http://www.opensource-excellence.com}  * @author        Created on 15-Nov-2010  * @license GNU/GPL http://www.gnu.org/copyleft/gpl.html  *  *  *  This program is free software: you can redistribute it and/or modify  *  it under the terms of the GNU General Public License as published by  *  the Free Software Foundation, either version 3 of the License, or  *  (at your option) any later version.  *  *  This program is distributed in the hope that it will be useful,  *  but WITHOUT ANY WARRANTY; without even the implied warranty of  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  *  GNU General Public License for more details.  *  *  You should have received a copy of the GNU General Public License  *  along with this program.  If not, see <http://www.gnu.org/licenses/>.  *  @Copyright Copyright (C) 2010- Open Source Excellence (R);*//*** access Joomla's configuration file ***/// Set flag that this is a parent filedefine('_JEXEC', 1);define('JPATH_BASE', dirname(dirname(dirname(dirname(__FILE__)))));define('DS', DIRECTORY_SEPARATOR);require_once(JPATH_BASE.DS.'includes'.DS.'defines.php');require_once(JPATH_BASE.DS.'includes'.DS.'framework.php');/** * CREATE THE APPLICATION * * NOTE : */$mainframe= & JFactory :: getApplication('site');jimport('joomla.plugin.helper');/*** END of Joomla config ***/
$subscription_id = (int)JRequest::getCmd('x_subscription_id');
// Check to see if we got a valid subscription ID.
// If so, do something with it.
if ($subscription_id)
{
    // Get the response code. 1 is success, 2 is decline, 3 is error
    $response_code = (int) JRequest::getCmd('x_response_code');
    // Get the reason code. 8 is expired card.	$reason_code = (int) JRequest::getCmd('x_response_reason_code');
	header("HTTP/1.0 200 OK");	//global $mosConfig_absolute_path, $mosConfig_live_site, $mosConfig_lang, $database, $mailfrom, $fromname;		/*** OSE part ***/	require_once(JPATH_BASE.DS."components".DS."com_osemsc".DS."init.php");	/*** END OSE part ***/
	// Get the response code. 1 is success, 2 is decline, 3 is error
    //$response_code = (int) $_POST['x_response_code'];
    // Get the reason code. 8 is expired card.
    //$reason_code = (int) $_POST['x_response_reason_code'];	// Get the Order Details from the database
    $db = oseDB::instance();	$where= array();	$where[]= "`payment_serial_number`=".$db->quote($subscription_id);	//$where[] = "`entry_type`= 'msc'" ;	$payment= oseRegistry :: call('payment');	$orderInfo = $payment->getOrder($where, 'obj');
        if(!empty($orderInfo))    {    	// $invoice =  $db->quote( $db->getEscaped($invoice));		//$invoice =  $db->quote($invoice);	    $order_id = $orderInfo->order_id;	    $member_id = $orderInfo->user_id;			//$msc_id = $results->msc_id;		$payment= oseRegistry :: call('payment')->getInstance('Order');	    if ($response_code == 1)	    {	        // Approved!	        			//$payment->updateOrder($order_id, "confirmed");			$payment->confirmOrder($order_id, array());			//OSEMSCAPI::order_status_changed($subscription_id, "c", $order_id);	    }	    else if ($response_code == 2 || ($response_code == 3 && $reason_code == 8))	    {			//OSEMSCAPI::order_status_changed($subscription_id, "p");			//OSEMSCAPI::email_user($user_id,$msc_id, "invalidcard", null);		        // Declined	        $payment->updateOrder($order_id, "pending");	    }	    else 	    {	    	 $payment->updateOrder($order_id, "pending");	    	//OSEMSCAPI::order_status_changed($subscription_id, "p");			//OSEMSCAPI::email_user($user_id,$msc_id, "cancel", null);		    }    }
}
?>