/*
 * File: app/model/juser.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.juser', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'juser_name',
                type: 'string'
            },
            {
                name: 'juser_username',
                type: 'string'
            },
            {
                name: 'juser_email',
                type: 'string'
            },
            {
                name: 'juser_password1',
                type: 'string'
            },
            {
                name: 'juser_password2',
                type: 'string'
            }
        ],
        validations: [
            {
                type: 'format',
                matcher: /([a-zA-Z0-9\.])+/,
                field: 'juser_name'
            },
            {
                type: 'format',
                matcher: /([a-zA-Z0-9\.])+/,
                field: 'juser_username'
            },
            {
                type: 'email',
                field: 'juser_email'
            },
            {
            	type: 'format',
            	matcher: /([a-zA-Z0-9\.])+/,
                field: 'juser_password1'
            },
            {
                type: 'password',
                field: 'juser_password2',
                message: ' is not equal Password'
            }
        ]
    },

    validate: function() {

        var errors      = Ext.create('Ext.data.Errors'),
            validations = this.getValidations().items,
            validators  = Ext.data.Validations,
            length, validation, field, valid, type, i;

        if (validations) {
            length = validations.length;

            for (i = 0; i < length; i++) {
                validation = validations[i];
                field = validation.field || validation.name;
                type  = validation.type;

                if(type == 'password') {
                    valid = validators[type](validation, this.get(field),this);
                } else {
                    valid = validators[type]( validation, this.get(field) );
                }

                if (!valid) {
                    errors.add(Ext.create('Ext.data.Error', {
                        field  : field,
                        message: validation.message || validators.getMessage(type)
                    }));
                }
            }
        }

        return errors;

    }

});