/*
 * File: app/model/stateStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.stateModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'firstname',
                type: 'string'
            },
            {
                name: 'lastname',
                type: 'string'
            },
            {
                name: 'addr1',
                type: 'string'
            },
            {
                name: 'addr2',
                type: 'string'
            },
            {
                name: 'country',
                type: 'string'
            },
            {
                name: 'state',
                type: 'string'
            },
            {
                name: 'postcode',
                type: 'string'
            }
        ]
    }
});