/*
 * File: app/view/OptionItem.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mem.orderitem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.orderitem',

    config: {
        padding: 10,
        layout: {
            type: 'hbox'
        },
        items: [
            {xtype: 'container',itemId: 'create_date',flex:1},
            {xtype: 'container',itemId: 'order_id',flex:1},
            //{xtype: 'container',itemId: 'payment',flex:1},
            //{xtype: 'container',itemId: 'order_status',flex:1},
            {
            	xtype: 'container',
            	width:80,
            	items:[{
            		xtype: 'button',ui:'confirm-small',itemId: 'action',text:'PDF',
            		order_id:0,
            		handler: function(btn)	{
            			var me = this.up('orderitem');
            			Ext.create('Ext.form.Panel',{
            				items:[{
            					xtype: 'textfield',
            					label: 'Order ID',
            					readOnly: true,
            					name: 'order_id'
            				},{
            					xtype: 'textfield',
            					label: 'Payment Method',
            					readOnly: true,
            					name: 'payment'
            				},{
            					xtype: 'textfield',
            					label: 'Order Status',
            					readOnly: true,
            					name: 'order_status'
            				},{
            					xtype: 'toolbar',
            	                docked: 'top',
            	                title: 'Order Information',
            	                layout: {
            	                    pack: 'end',
            	                    type: 'hbox'
            	                },
            	                items: [{
            	                	xtype: 'button',
                                    ui: 'confirm',
                                    text: 'Detail',
                                    handler: function(btn)	{
                                    	window.open(
                        					getCurrentUrl()+'index.php?option=com_osemsc&controller=member&task=action&action=member.order.orderViewPDF&order_id='+me.getRecord().get('order_id')
                        					,'win1'
                        					,'status=no,toolbar=no,scrollbars=yes,titlebar=no,menubar=no,resizable=yes,width=640,height=480,directories=no,location=no'
                        				);

                        				return false;
                                    }
            	                }]
            				}],
            				width: 390,
            				height: 300,
            				hideOnMaskTap:true,
            				defaults: {labelWidth: 160},
            				modal: true,
            				listeners: {
            					painted: function(f)	{
            						f.setRecord(me.getRecord());
            						
            					}
            				}
            			}).showBy(btn);
            		}
            	}]
            }
        ],
        listeners: [
            {
                fn: 'painted',
                event: 'painted'
            }
            
            
        ]
    },

 
    painted: function()	{
    	
    },
    
    updateRecord: function(record) {
    	if(record.get('order_status') != Joomla.JText._('CONFIRMED'))	{
    		this.down('#action').hide();
    	}	else	{
    		this.down('#action').order_id = record.get('order_id');
    	}
    	this.down('#create_date').setHtml(record.get('create_date'));
    	this.down('#order_id').setHtml(Joomla.JText._('ORDER_ID') + ': ' + record.get('order_id'));
    	//this.down('#payment').setHtml(record.get('payment'));
    	//this.down('#order_status').setHtml(record.get('order_status'));
    	
    }

});