/*
 * File: app/model/stateStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.mem.orderModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {name: 'order_id', type: 'int', mapping: 'order_id'}
		    ,{name: 'create_date', type: 'string', mapping: 'create_date'}
		    ,{name: 'amount', type: 'string', mapping: 'payment_price'}
		    ,{name: 'payment', type: 'string', mapping: 'payment_method'}
		    ,{name: 'order_status', type: 'string', mapping: 'order_status'}
		    ,{name: 'params', type: 'string', mapping: 'params'}
        ]
    }
});