<?php

defined( '_JEXEC' ) or die( 'Restricted access' );

// Define some properties
define('OSEEMAIL_USER_USERNAME', JText::_('JOOMLA_USERNAME'));
define('OSEEMAIL_USER_NAME', JText::_('JOOMLA_USER_NAME'));
define('OSEEMAIL_USER_PASSWORD', JText::_('JOOMLA_USER_PASSWORD'));
define('OSEEMAIL_USER_EMAIL', JText::_('JOOMLA_USER_EMAIL'));
define('OSEEMAIL_USER_USER_STATUS', JText::_('JOOMLA_USER_STATUS'));
define('OSEEMAIL_USER_FIRSTNAME', JText::_('USER_FIRST_NAME'));
define('OSEEMAIL_USER_LASTNAME', JText::_('USER_LAST_NAME'));
define('OSEEMAIL_USER_PRIMARY_CONTACT', JText::_('USER_PRIMARY_CONTACT'));
define('OSEEMAIL_USER_COMPANY', JText::_('USER_COMPANY'));
define('OSEEMAIL_USER_ADDRESS1', JText::_('USER_ADDRESS1'));
define('OSEEMAIL_USER_ADDRESS2', JText::_('USER_ADDRESS2'));
define('OSEEMAIL_USER_CITY', JText::_('USER_CITY'));
define('OSEEMAIL_USER_STATE', JText::_('USER_STATE'));
define('OSEEMAIL_USER_COUNTRY', JText::_('USER_COUNTRY'));
define('OSEEMAIL_USER_POSTCODE', JText::_('USER_POSTCODE'));
define('OSEEMAIL_USER_TELEPHONE', JText::_('USER_TELEPHONE'));
define('OSEEMAIL_USER_USER_ID', JText::_('USER_USER_ID'));

define('OSEEMAIL_MEMBER_START_DATE', JText::_('MEMBER_MEMBERSHIP_START_DATE'));
define('OSEEMAIL_MEMBER_EXPIRED_DATE', JText::_('MEMBER_MEMBERSHIP_EXPIRED_DATE'));
define('OSEEMAIL_MEMBER_PERIOD', JText::_('MEMBER_MEMBERSHIP_PERIOD'));
define('OSEEMAIL_MEMBER_MSC_TITLE', JText::_('MEMBERSHIP_TITLE'));
define('OSEEMAIL_MEMBER_MSC_DES', JText::_('MEMBERSHIP_DESCRIPTION'));

define('OSEEMAIL_ORDER_PAYMENT_CURRENCY', JText::_('CURRENCY'));
define('OSEEMAIL_ORDER_ORDER_ID', JText::_('ORDER_ID'));
define('OSEEMAIL_ORDER_PAYMENT_SERIAL_NUMBER', JText::_('ORDER_PAYMENT_SERIAL_NUMBER'));
define('OSEEMAIL_ORDER_ORDER_NUMBER', JText::_('ORDER_NUMBER'));
define('OSEEMAIL_ORDER_ORDER_STATUS', JText::_('ORDER_STATUS'));
define('OSEEMAIL_ORDER_PRICE', JText::_('MEMBERSHIP_PRICE'));
define('OSEEMAIL_ORDER_FINAL_PRICE', JText::_('MEMBERSHIP_FINAL_PRICE'));
define('OSEEMAIL_ORDER_PAYMENT_METHOD', JText::_('PAYMENT_METHOD'));
define('OSEEMAIL_ORDER_DATE', JText::_('ORDER_CREATE_DATE'));
define('OSEEMAIL_ORDER_GROSS_TAX', JText::_('ORDER_TAX'));
define('OSEEMAIL_ORDER_SUBTOTAL', JText::_('ORDER_SUBTOTAL'));
define('OSEEMAIL_ORDER_TOTAL', JText::_('ORDER_TOTAL'));
define('OSEEMAIL_ORDER_DISCOUNT', JText::_('ORDER_DISCOUNT'));
define('OSEEMAIL_ORDER_ITEMLIST', JText::_('ORDER_MEMBERSHIP_LIST'));
define('OSEEMAIL_ORDER_TABLE', JText::_('ORDER_TABLE'));
define('OSEEMAIL_ORDER_PAYMENT_MODE', JText::_('ORDER_PAYMENT_MODE'));
define('OSEEMAIL_ORDER_VAT_NUMBER', JText::_('VAT_NUMBER'));
define('OSEEMAIL_ORDER_RECURRING_PRICE', JText::_('ORDER_RECURRING_PRICE'));
define('OSEEMAIL_ORDER_RECURRING_FREQUENCY', JText::_('ORDER_RECURRING_FREQUENCY'));
define('OSEEMAIL_ORDER_CURRENT_DATE', JText::_('ORDER_CURRENT_DATE'));