INSERT INTO `#__bid_country` VALUES
(4,'AFGHANISTAN','AF',1),
(5,'ALAND ISLANDS','AX',0),
(6,'ALBANIA','AL',1),
(7,'ALGERIA','DZ',0),
(8,'AMERICAN SAMOA','AS',0),
(9,'ANDORRA','AD',0),
(10,'ANGOLA','AO',0),
(11,'ANGUILLA','AI',0),
(12,'ANTARCTICA','AQ',0),
(13,'ANTIGUA AND BARBUDA','AG',0),
(14,'ARGENTINA','AR',0),
(15,'ARMENIA','AM',0),
(16,'ARUBA','AW',0),
(17,'AUSTRALIA','AU',1),
(18,'AUSTRIA','AT',1),
(19,'AZERBAIJAN','AZ',0),
(20,'BAHAMAS','BS',0),
(21,'BAHRAIN','BH',0),
(22,'BANGLADESH','BD',0),
(23,'BARBADOS','BB',0),
(24,'BELARUS','BY',0),
(25,'BELGIUM','BE',0),
(26,'BELIZE','BZ',0),
(27,'BENIN','BJ',0),
(28,'BERMUDA','BM',0),
(29,'BHUTAN','BT',0),
(30,'BOLIVIA','BO',0),
(31,'BOSNIA AND HERZEGOVINA','BA',0),
(32,'BOTSWANA','BW',0),
(33,'BOUVET ISLAND','BV',0),
(34,'BRAZIL','BR',0),
(35,'BRITISH INDIAN OCEAN TERRITORY','IO',0),
(36,'BRUNEI DARUSSALAM','BN',0),
(37,'BULGARIA','BG',0),
(38,'BURKINA FASO','BF',0),
(39,'BURUNDI','BI',0),
(40,'CAMBODIA','KH',0),
(41,'CAMEROON','CM',0),
(42,'CANADA','CA',0),
(43,'CAPE VERDE','CV',0),
(44,'CAYMAN ISLANDS','KY',0),
(45,'CENTRAL AFRICAN REPUBLIC','CF',0),
(46,'CHAD','TD',0),
(47,'CHILE','CL',0),
(48,'CHINA','CN',0),
(49,'CHRISTMAS ISLAND','CX',0),
(50,'COCOS (KEELING) ISLANDS','CC',0),
(51,'COLOMBIA','CO',0),
(52,'COMOROS','KM',0),
(53,'CONGO','CG',0),
(54,'CONGO,THE DEMOCRATIC REPUBLIC OF THE','CD',0),
(55,'COOK ISLANDS','CK',0),
(56,'COSTA RICA','CR',0),
(57,'CROATIA','HR',0),
(58,'CUBA','CU',0),
(59,'CYPRUS','CY',0),
(60,'CZECH REPUBLIC','CZ',0),
(61,'DENMARK','DK',0),
(62,'DJIBOUTI','DJ',0),
(63,'DOMINICA','DM',0),
(64,'DOMINICAN REPUBLIC','DO',0),
(65,'ECUADOR','EC',0),
(66,'EGYPT','EG',0),
(67,'EL SALVADOR','SV',0),
(68,'EQUATORIAL GUINEA','GQ',0),
(69,'ERITREA','ER',0),
(70,'ESTONIA','EE',0),
(71,'ETHIOPIA','ET',0),
(72,'FALKLAND ISLANDS (MALVINAS)','FK',0),
(73,'FAROE ISLANDS','FO',0),
(74,'FIJI','FJ',0),
(75,'FINLAND','FI',0),
(76,'FRANCE','FR',1),
(77,'FRENCH GUIANA','GF',1),
(78,'FRENCH POLYNESIA','PF',0),
(79,'FRENCH SOUTHERN TERRITORIES','TF',0),
(80,'GABON','GA',0),
(81,'GAMBIA','GM',0),
(82,'GEORGIA','GE',0),
(83,'GERMANY','DE',1),
(84,'GHANA','GH',0),
(85,'GIBRALTAR','GI',0),
(86,'GREECE','GR',0),
(87,'GREENLAND','GL',0),
(88,'GRENADA','GD',0),
(89,'GUADELOUPE','GP',0),
(90,'GUAM','GU',0),
(91,'GUATEMALA','GT',0),
(92,'GUERNSEY','GG',0),
(93,'GUINEA','GN',0),
(94,'GUINEA-BISSAU','GW',0),
(95,'GUYANA','GY',0),
(96,'HAITI','HT',0),
(97,'HEARD ISLAND AND MCDONALD ISLANDS','HM',0),
(98,'HONDURAS','HN',0),
(99,'HONG KONG','HK',0),
(100,'HUNGARY','HU',0),
(101,'ICELAND','IS',0),
(102,'INDIA','IN',0),
(103,'INDONESIA','ID',0),
(104,'IRAN, ISLAMIC REPUBLIC OF','IR',0),
(105,'IRAQ','IQ',0),
(106,'IRELAND','IE',0),
(107,'ISLE OF MAN','IM',0),
(108,'ISRAEL','IL',0),
(109,'ITALY','IT',0),
(110,'JAMAICA','JM',0),
(111,'JAPAN','JP',0),
(112,'JERSEY','JE',0),
(113,'JORDAN','JO',0),
(114,'KAZAKHSTAN','KZ',0),
(115,'KENYA','KE',0),
(116,'KIRIBATI','KI',0),
(117,'KOREA, REPUBLIC OF','KR',0),
(118,'KUWAIT','KW',0),
(119,'KYRGYZSTAN','KG',0),
(120,'LATVIA','LV',0),
(121,'LEBANON','LB',0),
(122,'LESOTHO','LS',0),
(123,'LIBERIA','LR',0),
(124,'LIBYAN ARAB JAMAHIRIYA','LY',0),
(125,'LIECHTENSTEIN','LI',0),
(126,'LITHUANIA','LT',0),
(127,'LUXEMBOURG','LU',0),
(128,'MACAO','MO',0),
(129,'MACEDONI, THE FORMER YUGOSLAV REPUBLIC OF','MK',0),
(130,'MADAGASCAR','MG',0),
(131,'MALAWI','MW',0),
(132,'MALAYSIA','MY',0),
(133,'MALDIVES','MV',0),
(134,'MALI','ML',0),
(135,'MALTA','MT',0),
(136,'MARSHALL ISLANDS','MH',0),
(137,'MARTINIQUE','MQ',0),
(138,'MAURITANIA','MR',0),
(139,'MAURITIUS','MU',0),
(140,'MAYOTTE','YT',0),
(141,'MEXICO','MX',0),
(142,'MICRONESIA, FEDERATED STATES OF','FM',0),
(143,'MOLDOVA, REPUBLIC OF','MD',0),
(144,'MONACO','MC',0),
(145,'MONGOLIA','MN',0),
(146,'MONTENEGRO','ME',0),
(147,'MONTSERRAT','MS',0),
(148,'MOROCCO','MA',0),
(149,'MOZAMBIQUE','MZ',0),
(150,'MYANMAR','MM',0),
(151,'NAMIBIA','NA',0),
(152,'NAURU','NR',0),
(153,'NEPAL','NP',0),
(154,'NETHERLANDS','NL',0),
(155,'NETHERLANDS ANTILLES','AN',0),
(156,'NEW CALEDONIA','NC',0),
(157,'NEW ZEALAND','NZ',0),
(158,'NICARAGUA','NI',0),
(159,'NIGER','NE',0),
(160,'NIGERIA','NG',0),
(161,'NIUE','NU',0),
(162,'NORFOLK ISLAND','NF',0),
(163,'NORTHERN MARIANA ISLANDS','MP',0),
(164,'NORWAY','NO',0),
(165,'OMAN','OM',0),
(166,'PAKISTAN','PK',0),
(167,'PALAU','PW',0),
(168,'PALESTINIAN TERRITORY, OCCUPIED','PS',0),
(169,'PANAMA','PA',0),
(170,'PAPUA NEW GUINEA','PG',0),
(171,'PARAGUAY','PY',0),
(172,'PERU','PE',0),
(173,'PHILIPPINES','PH',0),
(174,'PITCAIRN','PN',0),
(175,'POLAND','PL',0),
(176,'PORTUGAL','PT',0),
(177,'PUERTO RICO','PR',0),
(178,'QATAR','QA',0),
(179,'REUNION','RE',0),
(180,'ROMANIA','RO',1),
(181,'RUSSIAN FEDERATION','RU',0),
(182,'RWANDA','RW',0),
(183,'SAINT HELENA','SH',0),
(184,'SAINT KITTS AND NEVIS','KN',0),
(185,'SAINT LUCIA','LC',0),
(186,'SAINT PIERRE AND MIQUELON','PM',0),
(187,'SAINT VINCENT AND THE GRENADINES','VC',0),
(188,'SAMOA','WS',0),
(189,'SAN MARINO','SM',0),
(190,'SAO TOME AND PRINCIPE','ST',0),
(191,'SAUDI ARABIA','SA',0),
(192,'SENEGAL','SN',0),
(193,'SERBIA','RS',0),
(194,'SEYCHELLES','SC',0),
(195,'SIERRA LEONE','SL',0),
(196,'SINGAPORE','SG',0),
(197,'SLOVAKIA','SK',0),
(198,'SLOVENIA','SI',0),
(199,'SOLOMON ISLANDS','SB',0),
(200,'SOMALIA','SO',0),
(201,'SOUTH AFRICA','ZA',0),
(202,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS',0),
(203,'SPAIN','ES',0),
(204,'SRI LANKA','LK',0),
(205,'SUDAN','SD',0),
(206,'SURINAME','SR',0),
(207,'SVALBARD AND JAN MAYEN','SJ',0),
(208,'SWAZILAND','SZ',0),
(209,'SWEDEN','SE',0),
(210,'SWITZERLAND','CH',1),
(211,'SYRIAN ARAB REPUBLIC','SY',0),
(212,'TAIWAN, PROVINCE OF CHINA','TW',0),
(213,'TAJIKISTAN','TJ',0),
(214,'TANZANIA, UNITED REPUBLIC OF','TZ',0),
(215,'THAILAND','TH',0),
(216,'TIMOR-LESTE','TL',0),
(217,'TOGO','TG',0),
(218,'TOKELAU','TK',0),
(219,'TONGA','TO',0),
(220,'TRINIDAD AND TOBAGO','TT',0),
(221,'TUNISIA','TN',0),
(222,'TURKEY','TR',0),
(223,'TURKMENISTAN','TM',0),
(224,'TURKS AND CAICOS ISLANDS','TC',0),
(225,'TUVALU','TV',0),
(226,'UGANDA','UG',0),
(227,'UKRAINE','UA',0),
(228,'UNITED ARAB EMIRATES','AE',0),
(229,'UNITED KINGDOM','GB',1),
(230,'UNITED STATES','US',1),
(231,'UNITED STATES MINOR OUTLYING ISLANDS','UM',0),
(232,'URUGUAY','UY',0),
(233,'UZBEKISTAN','UZ',0),
(234,'VANUATU','VU',0),
(235,'VATICAN CITY STATE (HOLY SEE)','VA',0),
(236,'VENEZUELA','VE',0),
(237,'VIET NAM','VN',0),
(238,'VIRGIN ISLANDS, BRITISH','VG',0),
(239,'VIRGIN ISLANDS, U.S.','VI',0),
(240,'WALLIS AND FUTUNA','WF',0),
(241,'WESTERN SAHARA','EH',0),
(242,'YEMEN','YE',0),
(243,'ZAMBIA','ZM',0),
(244,'ZIMBABWE','ZW',0);

INSERT INTO `#__bid_currency` (`id`, `name`,`ordering`,`convert`,`default`) VALUES
(1, 'USD', 4, 0.93406, NULL),
(2, 'EUR', 5, 1.23669, NULL),
(3, 'CHF', 2, 1.02250, NULL),
(4, 'AUD', 3, 1.00000, 1);

INSERT INTO `#__bid_mails` VALUES
(2,'new_message','<p>Dear %NAME%  %SURNAME%,  </p><p>&nbsp;You received a new reply to your bid regarding the Auction: &quot;%AUCTIONTITLE% &quot;</p><p> You can see the message here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','New message regarding Auction %AUCTIONTITLE%',1),
(3,'new_bid','<p>Dear %NAME%  %SURNAME%,  </p><p>&nbsp;You received a new bid to your bid regarding the Auction: &quot;%AUCTIONTITLE% &quot;</p><p> You can see the bid here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster </p>','New bid on your Auction %AUCTIONTITLE%',1),
(4,'bid_accepted','<p>Dear %NAME% %SURNAME%,  </p><p>&nbsp;Your Bid for the auction %AUCTIONTITLE% won!&nbsp;</p><p>Congratulations!!</p><p>&nbsp;</p><p>  You can get more details on the webpage  %AUCTIONLINK%</p><p>Best Regards,</p><p>The Webmaster </p>','Your Bid was accepted on the Auction %AUCTIONTITLE%',1),
(5,'bid_lost','<p>Dear %NAME% %SURNAME%,</p><p>  Unfortunately, your Bid for the auction %AUCTIONTITLE% has lost </p><p>  You can get more details on the webpage  %AUCTIONLINK%</p><p>Best Regards,</p><p>The Webmaster </p><p>&nbsp;</p>','Informations about your bid on %AUCTIONTITLE%',1),
(8,'new_bid_auto_bin','<p>Dear %NAME% %SURNAME%,</p><p>  You recieved a BIN Bid for your auction %AUCTIONTITLE% and it was automatically accepted!  </p><p>You can get more details on the webpage  %AUCTIONLINK%</p><p>Best Regards,</p> <p>The Webmaster </p> <p>&nbsp;</p>','A BIN bid on %AUCTIONTITLE% was automatically accepted',1),
(9,'bin_accepted','Dear %NAME% %SURNAME%,  Your BIN Bid for the auction %AUCTIONTITLE% was accepted!  You can get more details on the webpage  %AUCTIONLINK%','Informations about your bid on %AUCTIONTITLE%',1),
(10,'bin_wait_approval','<p>Dear %NAME% %SURNAME%,  </p> <p>&nbsp;Your BIN Bid for the auction %AUCTIONTITLE% is waiting approval. You will be notify as soon as the Auctioneer takes a decision regarding your bid.</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your BIN bid on Auction %AUCTIONTITLE%',1),
(11,'alert_bin_accepted','<p>Dear %NAME% %SURNAME%,  </p> <p>On the Auction &quot;%AUCTIONTITLE%&quot; a BIN bid was accepted!&nbsp;</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your Watch on  %AUCTIONTITLE%',1),
(12,'bid_watchlist_canceled','<p>Dear %NAME% %SURNAME%,  </p> <p>The Auction %AUCTIONTITLE% was canceled!&nbsp;</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your Watched Auction  %AUCTIONTITLE%',1),
(13,'bid_canceled','<p>Dear %NAME% %SURNAME%,  </p> <p>The auction %AUCTIONTITLE% was canceled!</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your bid on  %AUCTIONTITLE%',1),
(14,'bid_watchlist_closed','<p>Dear %NAME% %SURNAME%,  </p> <p>The auction %AUCTIONTITLE% you were watching was closed!&nbsp;</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your Watched Auction %AUCTIONTITLE%',1),
(15,'bid_closed','<p>Dear %NAME% %SURNAME%,  </p><p>The auction %AUCTIONTITLE% was closed !</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your bid on %AUCTIONTITLE%',1),
(16,'bid_rate','<p>Dear %NAME% %SURNAME%,</p><p>  You recieved a rating for the auction %AUCTIONTITLE%  !</p> <p>  You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p> <p>&nbsp;</p>','New Rating recieved',1),
(17,'bid_admin_message','<p>Dear %NAME% %SURNAME%,  </p><p>You recieved a message from one of the Administrators regarding your auction %AUCTIONTITLE%  !</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','New Message from Webmaster regarding %AUCTIONTITLE%',1),
(18,'bid_your_will_expire','<p>Dear %NAME% %SURNAME%,  </p><p>Your auction %AUCTIONTITLE% will soon expire !  </p><p>You can get more details on the webpage  %AUCTIONLINK%</p><p>Best Regards,</p> <p>The Webmaster </p> <p>&nbsp;</p>','Your Auction %AUCTIONTITLE% will soon expire',1),
(19,'bid_watchlist_will_expire','<p>Dear %NAME% %SURNAME%,  </p><p>The Action you watched: %AUCTIONTITLE% will soon expire !  </p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your watched Auction  %AUCTIONTITLE%',1),
(20,'bid_new_mybid','<p>Dear %NAME% %SURNAME%,  </p><p>you placed a new bid on : %AUCTIONTITLE%  !</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Bid placed on Auction %AUCTIONTITLE%',1),
(21,'proxy_ended','<p>Dear %NAME% %SURNAME%,  </p> <p>&nbsp;Your Proxy Bid for the auction %AUCTIONTITLE% has reached its limit.</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your proxybid on %AUCTIONTITLE%',1),
(22,'new_bid_watchlist','<p>Dear %NAME%  %SURNAME%,  </p><p>A new bid was placed on the Auction: &quot;%AUCTIONTITLE% &quot; that you were watching</p><p> You can see the bid here  %AUCTIONLINK%  </p><p> You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster </p>','Informations about your Watched Auction %AUCTIONTITLE%',1),
(23,'new_bid_bin','<p>Dear %NAME% %SURNAME%,  </p><p>A new BIN bid was placed on your Auction %AUCTIONTITLE%  !&nbsp; </p><p>It is waiting for your approval!&nbsp;</p><p>You can get more details on the webpage  %AUCTIONLINK%</p> <p>Best Regards,</p> <p>The Webmaster </p>','New BIN bid on your Auction %AUCTIONTITLE%',1),
(24,'alert_new_bid_bin','<p>Dear %NAME%  %SURNAME%,  </p> <p>A new BIN bid was placed on the Auction: &quot;%AUCTIONTITLE% &quot; that you were watching<br /> </p> <p> You can see the bid here  %AUCTIONLINK%  </p> <p> You must login to read the message.</p> <p>Best Regards,</p> <p>The Webmaster </p>','Informations about your Watched Auction %AUCTIONTITLE%',1),
(25,'bid_choose_winner','<p>Dear %NAME% %SURNAME%,  </p><p>&nbsp;Your auction %AUCTIONTITLE% awaits that you choose a winner.&nbsp;</p><p>You can do this by visiting %AUCTIONLINK%</p><p>Best Regards,</p><p>The Webmaster </p>','A bid won for your auction %AUCTIONTITLE%',1),
(26,'bid_offer_winner_to_owner','<p>Dear %NAME% %SURNAME%,  </p><p>&nbsp;Your auction %AUCTIONTITLE% has a winning bid.&nbsp;</p><p>You can see it by visiting %AUCTIONLINK%</p><p>Best Regards,</p><p>The Webmaster </p>','Please choose a winner for your auction %AUCTIONTITLE%',1),
(27,'bid_offer_no_winner_to_owner','<p>Dear %NAME% %SURNAME%,  </p><p>&nbsp;Your auction %AUCTIONTITLE% did not had a winning bid. It was closed without one&nbsp;</p><p>You can visit %AUCTIONLINK%</p><p>Best Regards,</p><p>The Webmaster </p>','No winner for your auction %AUCTIONTITLE%',1),
(28,'bid_outbid','<p>Dear %NAME% %SURNAME%,  </p><p>&nbsp;Your bid on %AUCTIONTITLE% was outbid.&nbsp;</p><p>You can rebid here %AUCTIONLINK%</p><p>Best Regards,</p><p>The Webmaster </p>','Your bid on %AUCTIONTITLE% was outbidded',1),
(29,'bid_reserve_not_met','<p>Dear %NAME%  %SURNAME%,  </p> <p>Your  Auction: &quot;%AUCTIONTITLE% &quot; expired and the reserve price was not met<br /> </p> <p> You can see the bid here  %AUCTIONLINK%  </p> <p> You must login to choose winner.</p> <p>Best Regards,</p> <p>The Webmaster </p>','Your Auction %AUCTIONTITLE% did not met reserve price',1),
(30,'bid_payment_received','<p>Dear %NAME%  %SURNAME%,  </p> <p>Your  Payment was received<br /> </p>   <p>Best Regards,</p> <p>The Webmaster </p>','Your Payment is received',1),
(31,'report_notify','<p>Dear %NAME%  %SURNAME%,  </p><p>&nbsp;The Auction: &quot;%AUCTIONTITLE% &quot;</p><p> was reported as abusive. You can see the message here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','The Auction: %AUCTIONTITLE%  was reported as abusive',1),
(32,'suggest_accepted','<p>Dear %NAME%  %SURNAME%,  </p><p>Your price suggestion on &quot;%AUCTIONTITLE% &quot;</p><p> was accepted. You can see the suggestion here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','Your price suggestion on Auction: %AUCTIONTITLE%  was accepted',1),
(33,'suggest_rejected','<p>Dear %NAME%  %SURNAME%,  </p><p>Your price suggestion on &quot;%AUCTIONTITLE% &quot;</p><p> was rejected. You can see the suggestion here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','Your price suggestion on Auction: %AUCTIONTITLE%  was rejected',1),
(34,'suggest_success','<p>Dear %NAME%  %SURNAME%,  </p><p>A new price suggestion was received on &quot;%AUCTIONTITLE% &quot;</p><p> You can see the suggestions here  %AUCTIONLINK%  </p><p>&nbsp;You must login to see the suggestions.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','A new price suggestion on Auction: %AUCTIONTITLE%  was received',1),
(35,'suggest_reminder','<p>Dear %NAME%  %SURNAME%,  </p><p>Some price suggestions on &quot;%AUCTIONTITLE% &quot; are waitting to be accepted / reject </p><p> You can see the suggestions here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','Some price suggestions on Auction: %AUCTIONTITLE%  are waitting for moderation',1),
(36,'replysuggest_success','<p>Dear %NAME%  %SURNAME%,  </p><p>You have received a suggestion reply on &quot;%AUCTIONTITLE% &quot;</p><p> You can see the suggestions here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','You have received reply to suggestion: %AUCTIONTITLE%',1),
(37,'new_auction','<p>Dear %NAME%  %SURNAME%,  </p><p>Your auction &quot;%AUCTIONTITLE% &quot; was published </p><p> You can see the auction here  %AUCTIONLINK%  </p><p>&nbsp;You must login to read the message.</p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>','Your auction %AUCTIONTITLE% was published',1),
(38, 'bid_auction_banned', '<p>Dear %NAME%  %SURNAME%,  </p><p>Your auction "%AUCTIONTITLE% " was banned. </p><p> You can see the auction here  %AUCTIONLINK%  </p><p>Best Regards,</p><p>The Webmaster&nbsp;</p>', 'Your auction %AUCTIONTITLE% was banned', 1);

INSERT INTO `#__bid_profilefields_assoc` VALUES
(1,'country',''),
(2,'city',''),
(5,'verified',''),
(6,'powerseller',''),
(7,'paymentparam',''),
(8, 'name', ''),
(9, 'address', ''),
(10, 'surname', ''),
(11, 'paypalemail', '');

INSERT INTO `#__bid_paysystems`
(`id`, `paysystem`, `classname`, `enabled`, `params`, `ordering`, `isdefault`) VALUES
(1, 'Paypal', 'pay_paypal', 1, 'paypal_email=change@me.now\r\nuse_sandbox=0', NULL, 1),
(2, 'Moneybookers', 'pay_moneybookers', 1, 'email=change@me.now\n', NULL, 0),
(3, '2Checkout', 'pay_2checkout', 1, '', NULL, 0),
(4, 'SagePay', 'pay_sagepay', 0, 'vendor_name=\r\nencryption_password=\r\nreferrer_id=\r\nconfirmation_email=\r\nsend_email=1\r\nemail_message=\r\nallow_gift_aid=0\r\napply_avscv2=0\r\napply_3dsecure=0\r\nmode=live', NULL, 0),
(5, 'BankTransfer', 'pay_banktransfer', 0, 'bank_info=<p>info</p>', NULL, 0),
(6, 'SagePayments', 'pay_sagepayments', 0, 'Terminal_id=\r\nLogo_url=\r\nB_color=\r\nBF_color=\r\nM_color=\r\nF_color=', NULL, 0);

INSERT INTO `#__bid_pricing` (`id`, `itemname`, `pricetype`, `name`, `price`, `currency`, `enabled`, `params`, `ordering`) VALUES
(1, 'featured', 'fixed', 'Featured Auction', 29.99, 'EUR', 1, 'price_powerseller="19.99"\nprice_verified="9.99"\ncategory_pricing_enabled=', 2),
(2, 'listing', 'fixed', 'Pay per Listing', 10.00, 'CHF', 0, 'price_powerseller=""\nprice_verified=""\ncategory_pricing_enabled=', 1),
(3, 'comission', 'percent', 'Earn Commission', 10.00, '', 1, '\n[buyer]\ndefault_price="5"\nprice_powerseller="2"\nprice_verified="3"\ncategory_pricing_enabled=""\nemail_text="PHA+SGVsbG8gJVNVUk5BTUUlLGE8L3A+DQo8cD7CoDwvcD4NCjxwPmFkIC0gJUJBTEFOQ0UlPC9wPg0KPHA+YXMgLSAlTElOSyU8L3A+DQo8cD5kYTwvcD4NCjxwPnNkPC9wPg0KPHA+YXM8L3A+"\n\n[seller]\ndefault_price="8"\nprice_powerseller="7"\nprice_verified="6"\ncategory_pricing_enabled=\nemail_text="PHA+SGVsbG8gJVNVUk5BTUUlLGE8L3A+DQo8cD7CoHF3ZTwvcD4NCjxwPmFkIC0gJUJBTEFOQ0UlPC9wPg0KPHA+YXMgLSAlTElOSyU8L3A+DQo8cD5kYTwvcD4NCjxwPnNkPC9wPg0KPHA+YXM8L3A+"', 2),
(4, 'contact', 'fixed', 'Pay per Contact', 44.00, 'USD', 1, 'price_powerseller="4"\nprice_verified="2"\ncategory_pricing_enabled=', 2),
(5, 'bid', 'fixed', 'Pay per Bid', 55.00, 'USD', 0, 'price_powerseller="5"\nprice_verified="1"\ncategory_pricing_enabled=', 2);

INSERT INTO `#__bid_increment` (`id`, `min_bid`, `max_bid`, `value`) VALUES
(1, '0.01', '10.00', '0.10'),
(2, '10.01', '25.00', '0.50'),
(3, '25.01', '100.00', '1.00'),
(4, '100.01', '150.00', '2.00'),
(5, '150.01', '500.00', '5.00'),
(6, '500.01', '1500.00', '10.00'),
(7, '1500.01', '2500.00', '20.00');